import { TourConfig } from '../types'

const config: TourConfig = {
  id: 'crm-organization-form',
  pageTitle: 'Create / Edit Organization',
  steps: [
    {
      target: 'org-name',
      title: 'Organization Name',
      purpose: 'The name of the company, railway zone, or government body you are dealing with. Shown everywhere this organization is referenced — inquiries, tenders, quotations.',
      whatToEnter: 'Full official name, no abbreviations.',
      required: true,
      validExample: 'Northern Railway Headquarters',
      invalidExample: 'NR HQ (ambiguous abbreviation — hard to search/report on later)',
      why: 'This name prints on every quotation/PO generated for this organization.',
    },
    {
      target: 'org-type',
      title: 'Organization Type',
      purpose: 'Classifies the organization so the right fields (e.g. Railway Zone) appear and reports can group customers correctly.',
      required: true,
      options: [
        { value: 'PSU', meaning: 'Public Sector Undertaking — govt-owned company (e.g. BHEL, RITES).' },
        { value: 'Govt Department', meaning: 'A government department/ministry, not the Railways itself.' },
        { value: 'Railway', meaning: 'A Railway zone, division, or workshop. Reveals Railway Zone + Division/Workshop fields.' },
        { value: 'Private', meaning: 'A private company. No Railway Zone field shown.' },
        { value: 'Joint Venture', meaning: 'A JV between two or more entities.' },
        { value: 'Other', meaning: 'Anything not listed — a text box appears to specify it.' },
      ],
      after: 'Selecting Railway or Govt Department reveals the Railway Zone and Division/Workshop fields below.',
    },
    {
      target: 'org-parent',
      title: 'Parent Organization',
      purpose: 'Optional — link this organization to a larger parent body, e.g. a Division under a Railway Zone.',
      required: false,
      whatToEnter: 'Free text name of the parent org, if any. Leave blank if this organization has no parent.',
    },
    {
      target: 'org-railway-zone',
      title: 'Railway Zone',
      purpose: 'Only shown when Organization Type is Railway or Govt Department. Identifies which of the 17-odd Indian Railway zones this belongs to.',
      required: false,
      validExample: 'Northern Railway',
      why: 'Used to route/report inquiries and tenders by zone.',
    },
    {
      target: 'org-division',
      title: 'Division / Workshop',
      purpose: 'The specific division or workshop under the selected Railway Zone.',
      validExample: 'Agra Division',
    },
    {
      target: 'org-address',
      title: 'Address',
      purpose: 'Street/locality address — appears on quotations and POs as the delivery/billing reference.',
      whatToEnter: 'Building, street, area — not city/state (those are separate fields below).',
      advanceOnEnter: true,
    },
    {
      target: 'org-country',
      title: 'Country',
      purpose: 'Determines whether this is treated as a domestic or export customer downstream (e.g. on quotation GST handling).',
      required: false,
      whatToEnter: 'Defaults to India. Select Other to type a different country.',
    },
    {
      target: 'org-state',
      title: 'State / UT',
      validExample: 'Delhi, Maharashtra, Tamil Nadu',
    },
    {
      target: 'org-city',
      title: 'City',
      validExample: 'New Delhi',
    },
    {
      target: 'org-pin',
      title: 'PIN Code',
      whatToEnter: '6-digit Indian postal code.',
      validExample: '110001',
      invalidExample: '1100 (too short) or letters mixed in',
    },
    {
      target: 'org-phone',
      title: 'Official Phone',
      purpose: 'The organization\'s primary contact number — printed on quotations/POs as the official contact.',
      whatToEnter: 'Include country code, e.g. +91.',
      validExample: '+91 98765 43210',
      invalidExample: '98765 (incomplete — missing digits) or text characters',
      after: 'Click "+ Add phone" below to attach a second official number — it is stored as an additional/extra phone, not a duplicate of this one.',
      why: 'Format is checked before saving; an invalid number blocks the Save action with an error dialog.',
    },
    {
      target: 'org-email',
      title: 'Official Email',
      purpose: 'The organization\'s primary official email address.',
      whatToEnter: 'A standard email address, e.g. name@domain.com',
      validExample: 'info@northernrailway.gov.in',
      invalidExample: 'info@northernrailway (missing domain suffix)',
      after: 'Use "+ Add email" for a second official email — it goes into a separate additional-emails list, so it will not overwrite this one.',
      why: 'Duplicate emails across this org\'s own fields and its contacts are flagged in real time (amber highlight) and block saving until fixed.',
    },
    {
      target: 'org-gst',
      title: 'GST Number',
      purpose: 'The organization\'s GSTIN, used for tax-compliant invoicing.',
      whatToEnter: '15-character GSTIN.',
      validExample: '07AABCU9603R1ZW',
      invalidExample: 'A PAN number alone, or fewer/more than 15 characters',
      why: 'An invalid GSTIN format is rejected on save with an inline red error.',
    },
    {
      target: 'org-website',
      title: 'Website',
      required: false,
      validExample: 'https://northernrailway.gov.in',
      invalidExample: 'northernrailway (missing https://)',
    },
    {
      target: 'contact-name',
      title: 'Contact Name',
      purpose: 'The specific person at this organization you correspond with — e.g. a Purchase Officer or DEN — as distinct from the organization\'s own Official Phone/Email above.',
      required: true,
      validExample: 'Rajesh Kumar',
      why: 'A contact row with a name is saved as its own contact record when you click Save; a row left completely blank is simply skipped, not saved as empty.',
    },
    {
      target: 'contact-designation',
      title: 'Designation',
      required: false,
      validExample: 'DEN, Purchase Head, DGM',
    },
    {
      target: 'contact-department',
      title: 'Department',
      required: false,
      validExample: 'Procurement, Engineering',
    },
    {
      target: 'contact-mobile',
      title: 'Mobile',
      required: false,
      whatToEnter: 'Include country code, e.g. +91.',
      validExample: '+91 98765 43210',
      invalidExample: 'A number with missing digits or stray letters',
      after: 'Use "+ Add phone" below it for a second mobile number for this same person — stored as an additional number, not a replacement.',
      why: 'Duplicate mobile numbers across the organization\'s own fields and every contact are flagged live (amber highlight) and block saving.',
    },
    {
      target: 'contact-email',
      title: 'Email',
      required: false,
      validExample: 'rajesh.kumar@org.gov.in',
      after: 'Use "+ Add email" below it for a second email for this same person.',
    },
    {
      target: 'org-add-contact',
      title: '+ Add Contact',
      purpose: 'Adds another blank contact row so you can record more than one person for this organization.',
      after: 'Each filled-in row is saved as its own separate contact record when you click Save at the bottom of the form.',
    },
    {
      target: 'org-save',
      title: 'Save',
      purpose: 'Validates every field (required fields, formats, duplicates) and saves the organization and all its contacts together.',
      after: 'On success you return to the Organizations list. On any validation failure, an error dialog names exactly what to fix — nothing is saved until all fields pass.',
    },
  ],
}

export default config
