import { TourConfig } from '../types'

const config: TourConfig = {
  id: 'crm-quotation-form',
  pageTitle: 'Create Quotation',
  steps: [
    {
      target: 'inquiry-tab-Quotations',
      title: 'Step 1 — Open the Quotations tab',
      purpose: 'Quotations are created from inside an Inquiry, not as a standalone page. This tab lists every quotation (and its revisions) raised for this inquiry.',
      after: 'Click this tab, then click "+ Create Quote" to open the form covered by the rest of this tour.',
      autoActivate: true,
    },
    {
      target: 'quotation-create-btn',
      title: 'Step 2 — + Create Quote',
      purpose: 'Opens the new-quotation form below the button.',
      after: 'Clicking again while the form is open cancels and discards anything typed into it.',
      autoActivateOnAdvance: true,
    },
    {
      target: 'quot-type',
      title: 'Quotation Type',
      purpose: 'Decides the currency and tax handling for the whole quotation.',
      required: true,
      options: [
        { value: 'Domestic (INR)', meaning: 'Prices in ₹, GST fields (CGST/SGST or IGST) apply per line item.' },
        { value: 'Export (USD)', meaning: 'Prices in $, GST is skipped entirely — no GST% column, no GST Type field shown.' },
      ],
      after: 'Switching this after entering line items recalculates every row\'s tax and total automatically.',
    },
    {
      target: 'quot-gst-type',
      title: 'GST Type',
      purpose: 'Only shown for Domestic quotations. Determines whether tax splits into CGST+SGST or is charged as a single IGST.',
      options: [
        { value: 'CGST + SGST (Intra-state)', meaning: 'Buyer is in the same state as your registered GST — tax splits into two equal halves.' },
        { value: 'IGST (Inter-state)', meaning: 'Buyer is in a different state — single combined tax line.' },
      ],
      why: 'Wrong selection here does not block saving, but produces an incorrectly split tax on the printed PDF — check the buyer\'s state before choosing.',
    },
    {
      target: 'quot-date',
      title: 'Date of Quote',
      required: true,
      whatToEnter: 'Defaults to today. Change only if backdating/postdating a quote.',
    },
    {
      target: 'quot-tor-number',
      title: 'Technical Offer Number',
      required: false,
      purpose: 'Reference number of the Technical Offer Request sent to R&D for this inquiry, if one was raised.',
      whatToEnter: 'Auto-filled from the inquiry when a technical offer was sent; edit only if it needs correcting.',
    },
    {
      target: 'quot-tor-date',
      title: 'Technical Offer Date',
      required: false,
    },
    {
      target: 'quot-client-name',
      title: 'Customer / Client',
      purpose: 'The organization this quotation is addressed to. Prints as the customer name on the PDF.',
      required: true,
      whatToEnter: 'Auto-filled from the inquiry\'s linked organization — normally leave as-is.',
      why: 'Blank client name blocks saving with "Customer/Client is required."',
    },
    {
      target: 'quot-contact-name',
      title: 'Contact Person Name',
      required: false,
      purpose: 'The specific person at the client organization this quote is for — auto-filled from the inquiry\'s contact if one is set.',
    },
    {
      target: 'quot-contact-email',
      title: 'Contact Email',
      required: false,
      validExample: 'rajesh.kumar@org.gov.in',
    },
    {
      target: 'quot-contact-phone',
      title: 'Contact Phone',
      required: false,
      validExample: '+91 98765 43210',
    },
    {
      target: 'quot-item-name',
      title: 'Item Name',
      purpose: 'Each row is one product/service being quoted. Pick an existing product from the dropdown, or type a name that doesn\'t exist yet to add it to the product list on the fly.',
      required: true,
      whatToEnter: 'Start typing to search existing products, or type a brand-new name and confirm to create it.',
      validExample: 'High Speed Self-Propelled Rail-Road Vehicle (RRV) System',
      invalidExample: 'A row left completely blank — silently ignored, not treated as an error, so an unused extra row from "+ Add Line Item" never blocks saving.',
      why: 'A row with a name but no Qty/Price/GST% is rejected — see those fields below.',
    },
    {
      target: 'quot-item-model',
      title: 'Model No.',
      required: false,
      whatToEnter: 'The specific model/variant, if the item has one.',
      after: 'Picking an existing product auto-fills this from that product\'s own saved model number.',
      why: 'Adding the exact same product + model number twice in this quotation is blocked with a duplicate warning.',
    },
    {
      target: 'quot-item-qty',
      title: 'Qty',
      required: true,
      whatToEnter: 'A plain number — how many units of this item.',
      why: 'Blank on a row that has a name blocks saving with "Quantity is required."',
    },
    {
      target: 'quot-item-price',
      title: 'Price/Unit',
      required: true,
      whatToEnter: 'Price for one unit, in the quotation\'s currency (₹ for Domestic, $ for Export).',
      why: 'Blank on a row that has a name blocks saving with "Price/Unit is required." Drives the Subtotal and overall Grand Total below.',
    },
    {
      target: 'quot-item-gst',
      title: 'GST %',
      required: true,
      purpose: 'Only shown for Domestic quotations — Export quotations skip GST entirely.',
      whatToEnter: 'The GST rate for this item, e.g. 18.',
      why: 'Blank on a row that has a name blocks saving with "GST% is required."',
    },
    {
      target: 'quot-item-subtotal',
      title: 'Subtotal',
      purpose: 'Read-only — Qty × Price/Unit plus GST, recalculated automatically as you edit this row. Every row\'s Subtotal adds up to the Grand Total shown below the table.',
    },
    {
      target: 'quot-delivery-time',
      title: 'Delivery Time',
      required: true,
      whatToEnter: 'A number plus a time unit.',
      validExample: '7 days, 2 weeks, 3 months',
      invalidExample: '"soon" or "7" alone — no unit, so it fails the required format check',
      why: 'Must match a day/week/month/hour pattern or saving is blocked with an inline error.',
    },
    {
      target: 'quot-valid-until',
      title: 'Quote Validity Date',
      required: true,
      purpose: 'The date until which the quoted prices remain valid — printed on the PDF.',
    },
    {
      target: 'quot-discount',
      title: 'Discount',
      required: false,
      whatToEnter: 'A number plus a type — percent (%) or a flat amount in the quotation\'s currency.',
    },
    {
      target: 'quot-conditions',
      title: 'Quote Conditions',
      required: true,
      options: [
        { value: 'Standard T&C', meaning: 'The company\'s default standard terms.' },
        { value: 'Ex-works', meaning: 'Buyer takes delivery at the factory; pays freight/insurance separately.' },
        { value: 'FOR Destination', meaning: 'Freight paid, delivered to buyer\'s site.' },
        { value: 'FOB', meaning: 'Free On Board — seller\'s responsibility ends once goods are loaded onto the carrier.' },
        { value: 'CIF', meaning: 'Cost, Insurance and Freight — seller covers shipping and insurance to destination port.' },
        { value: 'Other/Custom', meaning: 'Reveals a free-text box below to type your own condition wording.' },
      ],
      why: 'Choosing Other/Custom without filling in the text box that appears still counts as blank and blocks saving.',
    },
    {
      target: 'quot-payment-terms',
      title: 'Payment Terms',
      required: true,
      purpose: 'Pick an existing saved payment term or type new wording — typing a new value and confirming adds it to the reusable Payment Terms list for future quotations.',
      validExample: '50% advance and 50% before delivery',
    },
    {
      target: 'quot-notes',
      title: 'Notes',
      required: false,
      purpose: 'Any additional remarks that should appear on the quotation, outside the standard terms/conditions.',
    },
    {
      target: 'quot-save',
      title: 'Save Quotation',
      purpose: 'Validates every required field and line item, then creates the quotation — it becomes downloadable as a PDF from the list below immediately after.',
      after: 'Any validation failure shows a dialog and highlights every offending field in red; nothing saves until all are fixed.',
    },
  ],
}

export default config
