"""Service Request email notifications, sent via Microsoft Graph `sendMail`
using the app-only token (no per-user delegated token involved).

The logo is sent as a CID inline attachment (not a remote <img src> URL) so it
renders regardless of the recipient's "block external images" setting — the
previous absolute-URL approach also depended on APP_BASE_URL being publicly
reachable, which it isn't in local dev (it's localhost).
"""
import base64
import logging
import datetime as _dt
from pathlib import Path
import httpx
from sqlalchemy.orm import Session

from app.core.config import settings
from app.auth.microsoft import get_app_graph_token
from app.modules.main.models.audit_log import AuditLog

logger = logging.getLogger(__name__)

_LOGO_CONTENT_ID = "premnathrail-logo"
_LOGO_PATH = Path(__file__).resolve().parent.parent / "static" / "logo.png"
_logo_b64_cache: str | None = None


def _logo_base64() -> str | None:
    global _logo_b64_cache
    if _logo_b64_cache is None:
        try:
            _logo_b64_cache = base64.b64encode(_LOGO_PATH.read_bytes()).decode("ascii")
        except OSError:
            logger.warning("Could not read logo file at %s; emails will send without it.", _LOGO_PATH)
            _logo_b64_cache = ""
    return _logo_b64_cache or None


def _logo_header() -> str:
    return f'<img src="cid:{_LOGO_CONTENT_ID}" alt="Premnathrail Rail" height="32" style="display:block;height:32px;width:auto">'


def _write_audit(db: Session, entity_id: int, action: str, performed_by_id: int | None, summary: str | None = None):
    db.add(AuditLog(entity_type="service_request", entity_id=entity_id, action=action, performed_by_id=performed_by_id, summary=summary))


async def _send_graph_mail(
    sender_email: str, subject: str, html_body: str, to_email: str, to_name: str,
    extra_attachments: list[dict] | None = None,
    sender_name: str = "Premnathrail Service Team",
) -> tuple[bool, str]:
    """extra_attachments: list of {"name": str, "content_type": str, "content_bytes": bytes} —
    sent as regular (non-inline) downloadable file attachments, e.g. a generated report."""
    try:
        token = await get_app_graph_token()
    except Exception as exc:
        return False, f"Graph token error: {exc}"

    message: dict[str, object] = {
        "subject": subject,
        "from": {"emailAddress": {"name": sender_name, "address": sender_email}},
        "body": {"contentType": "HTML", "content": html_body},
        "toRecipients": [{"emailAddress": {"name": to_name, "address": to_email}}],
    }
    attachments: list[dict] = []
    logo_b64 = _logo_base64()
    if logo_b64:
        attachments.append({
            "@odata.type": "#microsoft.graph.fileAttachment",
            "name": "logo.png",
            "contentType": "image/png",
            "contentBytes": logo_b64,
            "isInline": True,
            "contentId": _LOGO_CONTENT_ID,
        })
    for att in extra_attachments or []:
        attachments.append({
            "@odata.type": "#microsoft.graph.fileAttachment",
            "name": att["name"],
            "contentType": att.get("content_type", "application/octet-stream"),
            "contentBytes": base64.b64encode(att["content_bytes"]).decode("ascii"),
        })
    if attachments:
        message["attachments"] = attachments
    payload = {"message": message, "saveToSentItems": True}
    try:
        async with httpx.AsyncClient(timeout=20) as client:
            resp = await client.post(
                f"https://graph.microsoft.com/v1.0/users/{sender_email}/sendMail",
                headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
                json=payload,
            )
        if resp.status_code in (200, 202):
            return True, ""
        return False, f"Graph error {resp.status_code}: {resp.text[:300]}"
    except Exception as exc:
        return False, f"Request error: {exc}"


def _sr_email_table_row(label: str, value: str, shaded: bool) -> str:
    bg = "background:#f8fafc;" if shaded else ""
    return f'<tr style="{bg}"><td style="padding:10px 14px;color:#64748b;width:180px">{label}</td><td style="padding:10px 14px;font-weight:700">{value}</td></tr>'


def _wrap_email_html(body_content: str) -> str:
    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#f1f5f9">
<div style="font-family:Arial,sans-serif;max-width:640px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.08)">
  <div style="background:#fff;padding:20px 28px;border-bottom:3px solid #f97316">{_logo_header()}</div>
  <div style="padding:32px 28px">{body_content}</div>
  <div style="background:#f8fafc;padding:16px 28px;border-top:1px solid #e2e8f0">
    <p style="font-size:11px;color:#94a3b8;margin:0;text-align:center">This email was auto-generated by Premnathrail ERP Portal. Please do not reply directly to this email.</p>
  </div>
</div>
</body></html>"""


async def send_client_sr_email(db: Session, sr, project, actor_id: int, actor_name: str, event_type: str) -> bool:
    """Send the client-facing "created"/"closed" notification for a Service Request."""
    client_email = sr.reported_by_email
    sender_email = settings.SENDER_EMAIL
    if not client_email or not sender_email:
        return False

    client_name = sr.reported_by_name or (project.client_company if project else None) or "Valued Customer"

    if event_type == "created":
        subject = f"Service Request Registered — {sr.request_number}"
        date_val = sr.created_at.strftime("%d %b %Y") if sr.created_at else _dt.date.today().strftime("%d %b %Y")
        body_content = f"""
    <p style="margin:0 0 16px">Dear <strong>{client_name}</strong>,</p>
    <p style="margin:0 0 20px;line-height:1.7">We would like to inform you that work on your requested service has officially started.</p>
    <table style="width:100%;border-collapse:collapse;font-size:13px;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;margin-bottom:24px">
      {_sr_email_table_row("Service Request ID", sr.request_number, True)}
      {_sr_email_table_row("Service", sr.issue_title or "—", False)}
      {_sr_email_table_row("Start Date", date_val, True)}
    </table>
    <p style="margin:0 0 28px;line-height:1.7">Our team is currently working on the requested requirements. We will keep you informed of any updates.</p>
    <p style="margin:0">Regards,<br><strong>Premnathrail Service Team</strong></p>"""
    else:
        subject = f"Service Request Completed — {sr.request_number}"
        date_val = _dt.date.today().strftime("%d %b %Y")
        body_content = f"""
    <p style="margin:0 0 16px">Dear <strong>{client_name}</strong>,</p>
    <p style="margin:0 0 20px;line-height:1.7">We are pleased to inform you that the requested service has been completed.</p>
    <table style="width:100%;border-collapse:collapse;font-size:13px;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;margin-bottom:24px">
      {_sr_email_table_row("Service Request ID", sr.request_number, True)}
      {_sr_email_table_row("Service", sr.issue_title or "—", False)}
      {_sr_email_table_row("Completion Date", date_val, True)}
    </table>
    <p style="margin:0 0 28px;line-height:1.7">Thank you for choosing our services.</p>
    <p style="margin:0">Regards,<br><strong>Premnathrail Service Team</strong></p>"""

    success, error_detail = await _send_graph_mail(sender_email, subject, _wrap_email_html(body_content), client_email, client_name)
    summary = (
        f"Client email ({event_type}) sent to {client_email}."
        if success
        else f"Client email ({event_type}) to {client_email} failed. {error_detail}"
    )
    _write_audit(db, sr.id, "email_sent" if success else "email_failed", actor_id, summary)
    return success


async def send_team_sr_notification(db: Session, sr, project, actor_id: int, actor_name: str, event_type: str = "created") -> None:
    """Send the internal team notification (to TEAM_EMAIL) for a Service Request."""
    team_email = settings.TEAM_EMAIL
    sender_email = settings.SENDER_EMAIL
    if not team_email or not sender_email:
        return

    proj_name = f"{project.serial_number} — {project.model_name}" if project else f"Project #{sr.project_id}"
    client_company = (project.client_company if project else None) or "—"
    priority_colors = {"critical": "#dc2626", "high": "#f97316", "medium": "#eab308", "low": "#22c55e"}
    priority_color = priority_colors.get((sr.priority or "medium").lower(), "#64748b")
    assigned = sr.assigned_to_name or "—"
    exp_attend = sr.expected_date_to_attend.strftime("%d %b %Y") if sr.expected_date_to_attend else "—"

    if event_type == "created":
        subject = f"[New SR] {sr.request_number} — {sr.issue_title or 'Service Request'}"
        header_label, header_bg = "New Service Request Assigned", "#0f172a"
        start_date = sr.created_at.strftime("%d %b %Y") if sr.created_at else _dt.date.today().strftime("%d %b %Y")
        body_content = f"""
    <p style="margin:0 0 20px;font-size:14px;color:#475569;line-height:1.7">A new service request has been assigned and work has been initiated.</p>
    <table style="width:100%;border-collapse:collapse;font-size:13px;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;margin-bottom:20px">
      {_sr_email_table_row("Service Request ID", sr.request_number, True)}
      {_sr_email_table_row("Client", client_company, False)}
      {_sr_email_table_row("Service", sr.issue_title or "—", True)}
      {_sr_email_table_row("Start Date", start_date, False)}
      {_sr_email_table_row("Machine / Asset", proj_name, True)}
      {_sr_email_table_row("Expected Attend", exp_attend, False)}
      {_sr_email_table_row("Assigned To", assigned, True)}
    </table>
    <p style="margin:0;font-size:14px;color:#1e293b">Regards,<br><strong>Premnathrail Engineering Works</strong></p>"""
    else:
        subject = f"[SR Closed] {sr.request_number} — {sr.issue_title or 'Service Request'}"
        header_label, header_bg = "Service Request Completed", "#064e3b"
        completion_date = _dt.date.today().strftime("%d %b %Y")
        body_content = f"""
    <p style="margin:0 0 20px;font-size:14px;color:#475569;line-height:1.7">The following service request has been successfully completed.</p>
    <table style="width:100%;border-collapse:collapse;font-size:13px;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;margin-bottom:20px">
      {_sr_email_table_row("Service Request ID", sr.request_number, True)}
      {_sr_email_table_row("Client", client_company, False)}
      {_sr_email_table_row("Service", sr.issue_title or "—", True)}
      {_sr_email_table_row("Completion Date", completion_date, False)}
      {_sr_email_table_row("Machine / Asset", proj_name, True)}
    </table>
    <p style="margin:0;font-size:14px;color:#1e293b">Regards,<br><strong>Premnathrail Engineering Works</strong></p>"""

    html = f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#f1f5f9">
<div style="font-family:Arial,sans-serif;max-width:660px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.08)">
  <div style="background:#fff;padding:20px 28px;border-bottom:3px solid #f97316">{_logo_header()}</div>
  <div style="background:{header_bg};padding:18px 28px;display:flex;align-items:center;justify-content:space-between">
    <div>
      <p style="color:#94a3b8;font-size:11px;margin:0 0 4px;text-transform:uppercase;letter-spacing:1px">{header_label}</p>
      <h2 style="color:#fff;margin:0;font-size:20px;font-weight:700">{sr.request_number}</h2>
    </div>
    <span style="background:{priority_color};color:#fff;font-size:11px;font-weight:700;padding:4px 12px;border-radius:20px;text-transform:uppercase">{(sr.priority or 'medium').upper()}</span>
  </div>
  <div style="padding:28px">{body_content}</div>
  <div style="background:#f8fafc;padding:14px 28px;border-top:1px solid #e2e8f0">
    <p style="font-size:11px;color:#94a3b8;margin:0;text-align:center">This is an automated internal notification from Premnathrail ERP Portal.</p>
  </div>
</div>
</body></html>"""

    success, error = await _send_graph_mail(sender_email, subject, html, team_email, "Service Team")
    if success:
        _write_audit(db, sr.id, "email_sent", actor_id, f"Team notification ({event_type}) sent to {team_email}.")
    else:
        logger.warning("Team SR notification failed: %s", error)
        _write_audit(db, sr.id, "email_failed", actor_id, f"Team notification ({event_type}) to {team_email} failed. {error}")


async def send_purchase_requisition_email(db: Session, pr, sr, project, materials, recipient_emails: list[str]) -> bool:
    """Best-effort notification to the Purchase department when a PR is raised
    from a Service Request's Materials tab. Failure is logged and recorded in
    the SR's audit trail but never raised — the PR itself is already saved by
    the time this runs (called from a BackgroundTask).

    Styled to match `send_team_sr_notification`'s internal-notification look
    (dark title bar + status badge, info table, boxed callout section) so
    Purchase gets the same visual language as the rest of the team emails."""
    sender_email = settings.SENDER_EMAIL
    if not sender_email or not recipient_emails:
        return False

    from app.modules.main.models.user import User
    raised_by = db.query(User).filter(User.id == pr.raised_by_id).first() if pr.raised_by_id else None
    raised_by_name = (raised_by.name or raised_by.email) if raised_by else "—"
    raised_date = pr.created_at.strftime("%d %b %Y") if pr.created_at else _dt.date.today().strftime("%d %b %Y")

    proj_name = f"{project.serial_number} — {project.model_name}" if project and project.model_name else (project.serial_number if project else f"Project #{sr.project_id}")
    client_name = project.client_company if project else "—"
    site_name = project.site_name if project else "—"

    materials_html = "".join(
        f'<p style="margin:0 0 8px;font-size:13.5px;color:#1e293b">{m.material_name}'
        f'<span style="color:#64748b"> — Qty: {m.quantity} {m.unit}</span></p>'
        for m in materials
    ) if materials else '<p style="margin:0;font-size:13.5px;color:#94a3b8">No materials listed.</p>'

    subject = f"New Purchase Requisition — {pr.pr_number} (SR {sr.request_number})"
    body_content = f"""
    <p style="margin:0 0 4px;font-size:14px;color:#1e293b;font-weight:700">Dear Purchase Team,</p>
    <p style="margin:0 0 20px;font-size:14px;color:#475569;line-height:1.7">A new purchase requisition has been raised from a Service Request's Materials list and is awaiting your review.</p>
    <table style="width:100%;border-collapse:collapse;font-size:13px;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;margin-bottom:20px">
      {_sr_email_table_row("Purchase Requisition", pr.pr_number, True)}
      {_sr_email_table_row("Service Request", sr.request_number, False)}
      {_sr_email_table_row("Client", client_name, True)}
      {_sr_email_table_row("Machine / Asset", proj_name, False)}
      {_sr_email_table_row("Site", site_name, True)}
      {_sr_email_table_row("Raised By", raised_by_name, False)}
      {_sr_email_table_row("Raised Date", raised_date, True)}
    </table>
    <p style="font-size:11px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:#64748b;margin:0 0 8px">Materials</p>
    <div style="border-left:4px solid #f97316;background:#f8fafc;padding:14px 16px;border-radius:0 8px 8px 0;margin-bottom:20px">
      {materials_html}
    </div>
    <p style="margin:0;font-size:14px;color:#1e293b">Regards,<br><strong>Premnathrail Engineering Works</strong></p>"""

    html = f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#f1f5f9">
<div style="font-family:Arial,sans-serif;max-width:660px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.08)">
  <div style="background:#fff;padding:20px 28px;border-bottom:3px solid #f97316">{_logo_header()}</div>
  <div style="background:#0f172a;padding:18px 28px;display:flex;align-items:center;justify-content:space-between">
    <div>
      <p style="color:#94a3b8;font-size:11px;margin:0 0 4px;text-transform:uppercase;letter-spacing:1px">New Purchase Requisition Raised</p>
      <h2 style="color:#fff;margin:0;font-size:20px;font-weight:700">{pr.pr_number}</h2>
    </div>
    <span style="background:#3b82f6;color:#fff;font-size:11px;font-weight:700;padding:4px 12px;border-radius:20px;text-transform:uppercase">Submitted</span>
  </div>
  <div style="padding:28px">{body_content}</div>
  <div style="background:#f8fafc;padding:14px 28px;border-top:1px solid #e2e8f0">
    <p style="font-size:11px;color:#94a3b8;margin:0;text-align:center">This is an automated internal notification from Premnathrail ERP Portal.</p>
  </div>
</div>
</body></html>"""

    any_success = False
    errors = []
    for email in recipient_emails:
        success, error = await _send_graph_mail(sender_email, subject, html, email, "Purchase Team")
        if success:
            any_success = True
        else:
            errors.append(f"{email}: {error}")

    if any_success:
        _write_audit(db, sr.id, "email_sent", None, f"Purchase requisition email ({pr.pr_number}) sent to {', '.join(recipient_emails)}.")
    else:
        logger.warning("Purchase requisition email failed: %s", "; ".join(errors))
        _write_audit(db, sr.id, "email_failed", None, f"Purchase requisition email ({pr.pr_number}) failed. {'; '.join(errors)}")
    return any_success


async def send_technical_offer_request_email(
    db: Session, entity_type: str, entity_id: int, offer_number: str,
    universal_id: str, org_name: str, project_name: str, documents_link: str,
    actor_id: int | None, actor_name: str,
    reference_documents: list[dict] | None = None,
    actor_email: str | None = None,
) -> tuple[bool, str]:
    """Emails R&D a link to the Technical Offer Request .docx (already uploaded to
    SharePoint by the caller — see technical_offer_docx.py / upload_file_to_sharepoint),
    with the offer number they must reference in their reply. Writes an AuditLog row
    either way (entity_type is "inquiry" or "tender"), which the Timeline tab picks up
    to show exactly when the request was sent.

    Sent "from" the acting user's own mailbox (actor_email) rather than the fixed
    SENDER_EMAIL, so R&D sees it came from whoever actually clicked Send — falls back
    to SENDER_EMAIL only if the caller didn't have the user's email on hand."""
    sender_email = actor_email or settings.SENDER_EMAIL
    rnd_email = settings.RND_EMAIL
    if not sender_email or not rnd_email:
        return False, "Sender or R&D email is not configured."

    subject = f"Technical Offer Request {offer_number} — {universal_id}"
    ref_docs_html = ""
    if reference_documents:
        items = "".join(
            f'<li style="margin:0 0 6px"><a href="{d["url"]}" style="color:#2563eb">{d["name"]}</a></li>'
            for d in reference_documents if d.get("url")
        )
        if items:
            ref_docs_html = f"""
    <p style="margin:0 0 8px;font-size:13.5px;color:#1e293b;font-weight:700">Reference Documents</p>
    <ul style="margin:0 0 20px;padding-left:20px;font-size:13.5px;color:#475569">{items}</ul>"""
    body_content = f"""
    <p style="margin:0 0 16px;font-size:14px;color:#1e293b;font-weight:700">Dear R&amp;D Team,</p>
    <p style="margin:0 0 20px;font-size:14px;color:#475569;line-height:1.7">
      A Technical Offer Request has been raised for the requirement below. The full details
      (Organization, Project, and Product Requirement) are in the document linked below.
    </p>
    <table style="width:100%;border-collapse:collapse;font-size:13px;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;margin-bottom:20px">
      {_sr_email_table_row("Technical Offer No.", offer_number, True)}
      {_sr_email_table_row("Reference ID", universal_id, False)}
      {_sr_email_table_row("Organization", org_name or "—", True)}
      {_sr_email_table_row("Project", project_name or "—", False)}
      {_sr_email_table_row("Raised By", actor_name, True)}
    </table>
    <p style="margin:0 0 8px;font-size:13.5px;color:#1e293b;font-weight:700">Please quote <span style="color:#f97316">{offer_number}</span> in your technical offer.</p>
    <p style="margin:0 0 20px;font-size:13.5px;color:#475569">Technical Offer Request document: <a href="{documents_link}" style="color:#2563eb">{documents_link}</a></p>
    {ref_docs_html}
    <p style="margin:0;font-size:14px;color:#1e293b">Regards,<br><strong>{actor_name}</strong></p>"""
    html = f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#f1f5f9">
<div style="font-family:Arial,sans-serif;max-width:660px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.08)">
  <div style="background:#fff;padding:20px 28px;border-bottom:3px solid #f97316">{_logo_header()}</div>
  <div style="background:#0f172a;padding:18px 28px">
    <p style="color:#94a3b8;font-size:11px;margin:0 0 4px;text-transform:uppercase;letter-spacing:1px">Technical Offer Request</p>
    <h2 style="color:#fff;margin:0;font-size:20px;font-weight:700">{offer_number}</h2>
  </div>
  <div style="padding:28px">{body_content}</div>
  <div style="background:#f8fafc;padding:14px 28px;border-top:1px solid #e2e8f0">
    <p style="font-size:11px;color:#94a3b8;margin:0;text-align:center">This is an automated notification from the Premnathrail CRM.</p>
  </div>
</div>
</body></html>"""

    success, error = await _send_graph_mail(
        sender_email, subject, html, rnd_email, "R&D Team",
        sender_name=actor_name if actor_email else "Premnathrail Service Team",
    )
    summary = (
        f"Technical Offer Request {offer_number} sent to {rnd_email} from {sender_email}."
        if success else
        f"Technical Offer Request {offer_number} to {rnd_email} failed. {error}"
    )
    db.add(AuditLog(
        entity_type=entity_type, entity_id=entity_id,
        action="technical_offer_sent" if success else "technical_offer_failed",
        performed_by_id=actor_id, summary=summary,
    ))
    return success, error
