"""Service Request email notifications, sent via Microsoft Graph `sendMail`
using the app-only token (no per-user delegated token involved).

Note: unlike the legacy app, this does NOT embed a logo image loaded from a
hardcoded relative filesystem path — that was a fragile coupling to the
legacy repo's worktree layout. We use a plain text header instead.
"""
import logging
import datetime as _dt
import httpx
from sqlalchemy.orm import Session

from app.core.config import settings
from app.auth.microsoft import get_app_graph_token
from app.modules.main.models.audit_log import AuditLog

logger = logging.getLogger(__name__)

_LOGO_HEADER = '<span style="font-size:16px;font-weight:700;color:#f97316">Premnathrail Engineering Works</span>'


def _write_audit(db: Session, entity_id: int, action: str, performed_by_id: int | None, summary: str | None = None):
    db.add(AuditLog(entity_type="service_request", entity_id=entity_id, action=action, performed_by_id=performed_by_id, summary=summary))


async def _send_graph_mail(sender_email: str, subject: str, html_body: str, to_email: str, to_name: str) -> tuple[bool, str]:
    try:
        token = await get_app_graph_token()
    except Exception as exc:
        return False, f"Graph token error: {exc}"

    payload = {
        "message": {
            "subject": subject,
            "from": {"emailAddress": {"name": "Premnathrail Service Team", "address": sender_email}},
            "body": {"contentType": "HTML", "content": html_body},
            "toRecipients": [{"emailAddress": {"name": to_name, "address": to_email}}],
        },
        "saveToSentItems": True,
    }
    try:
        async with httpx.AsyncClient(timeout=20) as client:
            resp = await client.post(
                f"https://graph.microsoft.com/v1.0/users/{sender_email}/sendMail",
                headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
                json=payload,
            )
        if resp.status_code in (200, 202):
            return True, ""
        return False, f"Graph error {resp.status_code}: {resp.text[:300]}"
    except Exception as exc:
        return False, f"Request error: {exc}"


def _sr_email_table_row(label: str, value: str, shaded: bool) -> str:
    bg = "background:#f8fafc;" if shaded else ""
    return f'<tr style="{bg}"><td style="padding:10px 14px;color:#64748b;width:180px">{label}</td><td style="padding:10px 14px;font-weight:700">{value}</td></tr>'


def _wrap_email_html(body_content: str) -> str:
    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#f1f5f9">
<div style="font-family:Arial,sans-serif;max-width:640px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.08)">
  <div style="background:#fff;padding:20px 28px;border-bottom:3px solid #f97316">{_LOGO_HEADER}</div>
  <div style="padding:32px 28px">{body_content}</div>
  <div style="background:#f8fafc;padding:16px 28px;border-top:1px solid #e2e8f0">
    <p style="font-size:11px;color:#94a3b8;margin:0;text-align:center">This email was auto-generated by Premnathrail ERP Portal. Please do not reply directly to this email.</p>
  </div>
</div>
</body></html>"""


async def send_client_sr_email(db: Session, sr, project, actor_id: int, actor_name: str, event_type: str) -> bool:
    """Send the client-facing "created"/"closed" notification for a Service Request."""
    client_email = sr.reported_by_email
    sender_email = settings.SENDER_EMAIL
    if not client_email or not sender_email:
        return False

    client_name = sr.reported_by_name or (project.client_company if project else None) or "Valued Customer"

    if event_type == "created":
        subject = f"Service Request Registered — {sr.request_number}"
        date_val = sr.created_at.strftime("%d %b %Y") if sr.created_at else _dt.date.today().strftime("%d %b %Y")
        body_content = f"""
    <p style="margin:0 0 16px">Dear <strong>{client_name}</strong>,</p>
    <p style="margin:0 0 20px;line-height:1.7">We would like to inform you that work on your requested service has officially started.</p>
    <table style="width:100%;border-collapse:collapse;font-size:13px;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;margin-bottom:24px">
      {_sr_email_table_row("Service Request ID", sr.request_number, True)}
      {_sr_email_table_row("Service", sr.issue_title or "—", False)}
      {_sr_email_table_row("Start Date", date_val, True)}
    </table>
    <p style="margin:0 0 28px;line-height:1.7">Our team is currently working on the requested requirements. We will keep you informed of any updates.</p>
    <p style="margin:0">Regards,<br><strong>Premnathrail Service Team</strong></p>"""
    else:
        subject = f"Service Request Completed — {sr.request_number}"
        date_val = _dt.date.today().strftime("%d %b %Y")
        body_content = f"""
    <p style="margin:0 0 16px">Dear <strong>{client_name}</strong>,</p>
    <p style="margin:0 0 20px;line-height:1.7">We are pleased to inform you that the requested service has been completed.</p>
    <table style="width:100%;border-collapse:collapse;font-size:13px;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;margin-bottom:24px">
      {_sr_email_table_row("Service Request ID", sr.request_number, True)}
      {_sr_email_table_row("Service", sr.issue_title or "—", False)}
      {_sr_email_table_row("Completion Date", date_val, True)}
    </table>
    <p style="margin:0 0 28px;line-height:1.7">Thank you for choosing our services.</p>
    <p style="margin:0">Regards,<br><strong>Premnathrail Service Team</strong></p>"""

    success, error_detail = await _send_graph_mail(sender_email, subject, _wrap_email_html(body_content), client_email, client_name)
    summary = (
        f"Client email ({event_type}) sent to {client_email}."
        if success
        else f"Client email ({event_type}) to {client_email} failed. {error_detail}"
    )
    _write_audit(db, sr.id, "email_sent" if success else "email_failed", actor_id, summary)
    return success


async def send_team_sr_notification(db: Session, sr, project, actor_id: int, actor_name: str, event_type: str = "created") -> None:
    """Send the internal team notification (to TEAM_EMAIL) for a Service Request."""
    team_email = settings.TEAM_EMAIL
    sender_email = settings.SENDER_EMAIL
    if not team_email or not sender_email:
        return

    proj_name = f"{project.serial_number} — {project.model_name}" if project else f"Project #{sr.project_id}"
    client_company = (project.client_company if project else None) or "—"
    priority_colors = {"critical": "#dc2626", "high": "#f97316", "medium": "#eab308", "low": "#22c55e"}
    priority_color = priority_colors.get((sr.priority or "medium").lower(), "#64748b")
    assigned = sr.assigned_to_name or "—"
    exp_attend = sr.expected_date_to_attend.strftime("%d %b %Y") if sr.expected_date_to_attend else "—"

    if event_type == "created":
        subject = f"[New SR] {sr.request_number} — {sr.issue_title or 'Service Request'}"
        header_label, header_bg = "New Service Request Assigned", "#0f172a"
        start_date = sr.created_at.strftime("%d %b %Y") if sr.created_at else _dt.date.today().strftime("%d %b %Y")
        body_content = f"""
    <p style="margin:0 0 20px;font-size:14px;color:#475569;line-height:1.7">A new service request has been assigned and work has been initiated.</p>
    <table style="width:100%;border-collapse:collapse;font-size:13px;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;margin-bottom:20px">
      {_sr_email_table_row("Service Request ID", sr.request_number, True)}
      {_sr_email_table_row("Client", client_company, False)}
      {_sr_email_table_row("Service", sr.issue_title or "—", True)}
      {_sr_email_table_row("Start Date", start_date, False)}
      {_sr_email_table_row("Machine / Asset", proj_name, True)}
      {_sr_email_table_row("Expected Attend", exp_attend, False)}
      {_sr_email_table_row("Assigned To", assigned, True)}
    </table>
    <p style="margin:0;font-size:14px;color:#1e293b">Regards,<br><strong>Premnathrail Engineering Works</strong></p>"""
    else:
        subject = f"[SR Closed] {sr.request_number} — {sr.issue_title or 'Service Request'}"
        header_label, header_bg = "Service Request Completed", "#064e3b"
        completion_date = _dt.date.today().strftime("%d %b %Y")
        body_content = f"""
    <p style="margin:0 0 20px;font-size:14px;color:#475569;line-height:1.7">The following service request has been successfully completed.</p>
    <table style="width:100%;border-collapse:collapse;font-size:13px;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;margin-bottom:20px">
      {_sr_email_table_row("Service Request ID", sr.request_number, True)}
      {_sr_email_table_row("Client", client_company, False)}
      {_sr_email_table_row("Service", sr.issue_title or "—", True)}
      {_sr_email_table_row("Completion Date", completion_date, False)}
      {_sr_email_table_row("Machine / Asset", proj_name, True)}
    </table>
    <p style="margin:0;font-size:14px;color:#1e293b">Regards,<br><strong>Premnathrail Engineering Works</strong></p>"""

    html = f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#f1f5f9">
<div style="font-family:Arial,sans-serif;max-width:660px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.08)">
  <div style="background:#fff;padding:20px 28px;border-bottom:3px solid #f97316">{_LOGO_HEADER}</div>
  <div style="background:{header_bg};padding:18px 28px;display:flex;align-items:center;justify-content:space-between">
    <div>
      <p style="color:#94a3b8;font-size:11px;margin:0 0 4px;text-transform:uppercase;letter-spacing:1px">{header_label}</p>
      <h2 style="color:#fff;margin:0;font-size:20px;font-weight:700">{sr.request_number}</h2>
    </div>
    <span style="background:{priority_color};color:#fff;font-size:11px;font-weight:700;padding:4px 12px;border-radius:20px;text-transform:uppercase">{(sr.priority or 'medium').upper()}</span>
  </div>
  <div style="padding:28px">{body_content}</div>
  <div style="background:#f8fafc;padding:14px 28px;border-top:1px solid #e2e8f0">
    <p style="font-size:11px;color:#94a3b8;margin:0;text-align:center">This is an automated internal notification from Premnathrail ERP Portal.</p>
  </div>
</div>
</body></html>"""

    success, error = await _send_graph_mail(sender_email, subject, html, team_email, "Service Team")
    if success:
        _write_audit(db, sr.id, "email_sent", actor_id, f"Team notification ({event_type}) sent to {team_email}.")
    else:
        logger.warning("Team SR notification failed: %s", error)
        _write_audit(db, sr.id, "email_failed", actor_id, f"Team notification ({event_type}) to {team_email} failed. {error}")
