"""Bulk import / Excel export for the Store Item Master.

Item codes are always generated by the app (an item_code column in the
file is ignored). A row whose item name AND technical specification (stored in `description`) both match an item that already exists — in the Item Master, or
earlier in the same file — is NOT saved; it comes back in `existing` with
the item it matched, so the user sees new and existing items side by side.
Rows with a problem (missing name, unknown UOM/type/category) come back in
`errors` with the reason. Valid new rows are created with an auto code."""
import csv
import io

from fastapi import APIRouter, Depends, File, HTTPException, Query, UploadFile
from fastapi.responses import StreamingResponse
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.core.permissions import require_app_access
from app.db.session import get_db
from app.modules.main.models.user import User
from app.modules.store.models.category import StoreItemCategory
from app.modules.store.models.item import StoreItem
from app.modules.store.routes.item_types import item_types
from app.modules.store.routes.uoms import uom_options
from app.modules.store.service import generate_item_code

# Registered before the items router so /export isn't read as /{item_id}.
router = APIRouter(prefix="/store/items", tags=["Store"])

COLUMNS = ["item_type", "category", "subcategory", "item_name", "uom", "technical_specification"]


def _spec(r: dict) -> str:
    """Technical specification cell; older files used a `description` column."""
    return r.get("technical_specification") or r.get("description") or ""
MAX_ROWS = 5000


def _read_rows(filename: str, raw: bytes) -> list[dict]:
    name = (filename or "").lower()
    if name.endswith((".xlsx", ".xlsm")):
        from openpyxl import load_workbook
        try:
            ws = load_workbook(io.BytesIO(raw), read_only=True, data_only=True).active
        except Exception:
            raise HTTPException(status_code=422, detail="Could not open the Excel file — save it as .xlsx (or CSV) and try again.")
        rows = list(ws.iter_rows(values_only=True))
        if not rows:
            return []
        headers = [str(h or "").strip().lower() for h in rows[0]]
        return [{headers[i]: ("" if v is None else str(v).strip()) for i, v in enumerate(r) if i < len(headers)} for r in rows[1:]]
    if not name.endswith(".csv"):
        raise HTTPException(status_code=422, detail="Upload a .csv or .xlsx file — download the template to start from the right columns.")
    try:
        text = raw.decode("utf-8-sig")
    except UnicodeDecodeError:
        raise HTTPException(status_code=422, detail="Could not read the file as UTF-8 text — save it as CSV (UTF-8) from Excel and try again.")
    reader = csv.DictReader(io.StringIO(text))
    return [{(k or "").strip().lower(): (v or "").strip() for k, v in r.items()} for r in reader]


def _type_value(raw: str, labels: dict[str, str]) -> str | None:
    """Accepts the code (tool_equipment) or the label (Tool & Equipment)."""
    if not raw:
        return "material"
    key = raw.strip().lower()
    for value, label in labels.items():
        if key in (value, label.lower(), label.lower().replace(" & ", " and ")):
            return value
    return None


@router.get("/import/template")
async def import_template(_user: User = Depends(require_app_access("store"))):
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(COLUMNS)
    w.writerow(["Material", "Hardware & Fasteners", "", "Hex Bolt M12x50", "NOS", "Zinc plated"])
    w.writerow(["Consumable", "PPE", "", "Safety Gloves", "PAIR", ""])
    return StreamingResponse(iter([buf.getvalue()]), media_type="text/csv",
                             headers={"Content-Disposition": 'attachment; filename="item_master_import_template.csv"'})


@router.post("/import")
async def import_items(
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    _user: User = Depends(require_app_access("store")),
):
    rows = _read_rows(file.filename, await file.read())
    if not rows:
        raise HTTPException(status_code=422, detail="The file has no data rows — fill in at least one item under the header row.")
    if len(rows) > MAX_ROWS:
        raise HTTPException(status_code=422, detail=f"The file has {len(rows)} rows — import at most {MAX_ROWS} at a time by splitting it.")
    if "item_name" not in rows[0] or "uom" not in rows[0]:
        raise HTTPException(status_code=422, detail="Missing the item_name / uom columns — download the template and keep its header row.")

    uoms = {o["value"] for o in uom_options(db)}
    labels = {t.value: t.label for t in item_types(db)}
    # Same name with a different technical specification is a different item (e.g. a different spec).
    by_name = {(n.strip().lower(), (d or '').strip().lower()): (c, n)
               for c, n, d in db.query(StoreItem.item_code, StoreItem.item_name, StoreItem.description).all()}
    top_cats = db.query(StoreItemCategory).filter(StoreItemCategory.parent_id.is_(None)).all()

    created, existing, errors = [], [], []
    seen_names: dict[str, int] = {}

    for idx, r in enumerate(rows, start=2):  # row 1 is the header
        name = r.get("item_name", "")
        if not any(r.values()):
            continue
        if not name:
            errors.append({"row": idx, "item_name": "", "reason": "Item name is empty — fill in item_name."})
            continue

        # Already exists → don't save, report it.
        key = (name.lower(), _spec(r).lower())
        match = by_name.get(key)
        if match:
            existing.append({"row": idx, "item_name": name, "existing_code": match[0], "existing_name": match[1],
                             "reason": "Same name and technical specification already exist"})
            continue
        if key in seen_names:
            existing.append({"row": idx, "item_name": name, "existing_code": None, "existing_name": name,
                             "reason": f"Repeats row {seen_names[key]} of this file"})
            continue

        uom = r.get("uom", "").upper()
        if not uom:
            errors.append({"row": idx, "item_name": name, "reason": "UOM is empty — fill in a unit like NOS, KG or MTR."})
            continue
        if uom not in uoms:
            errors.append({"row": idx, "item_name": name, "reason": f"UOM '{uom}' isn't in the unit list — add it from the UOM dropdown first, or use a listed unit."})
            continue
        item_type = _type_value(r.get("item_type", ""), labels)
        if not item_type:
            errors.append({"row": idx, "item_name": name, "reason": f"Item type '{r.get('item_type')}' isn't valid — use one of: {', '.join(labels.values())}."})
            continue

        category = subcategory = None
        if r.get("category"):
            cat = next((c for c in top_cats if c.name.lower() == r["category"].lower() and c.item_type == item_type), None)
            if not cat:
                allowed = ", ".join(c.name for c in top_cats if c.item_type == item_type)
                errors.append({"row": idx, "item_name": name, "reason": f"Category '{r['category']}' isn't a {labels[item_type]} category — use one of: {allowed}."})
                continue
            category = cat.name
            if r.get("subcategory"):
                sub = db.query(StoreItemCategory).filter(
                    StoreItemCategory.parent_id == cat.id, func.lower(StoreItemCategory.name) == r["subcategory"].lower()).first()
                if not sub:
                    from app.modules.store.routes.categories import _auto_code
                    sub = StoreItemCategory(name=r["subcategory"], code=_auto_code(db, r["subcategory"]), parent_id=cat.id, item_type=item_type)
                    db.add(sub)
                    db.flush()
                subcategory = sub.name
        elif r.get("subcategory"):
            errors.append({"row": idx, "item_name": name, "reason": "Subcategory given without a category — fill in the category too."})
            continue

        item = StoreItem(
            item_code=generate_item_code(db, item_type, category),
            item_name=name, item_type=item_type, category=category, subcategory=subcategory,
            description=_spec(r) or None, uom=uom,
        )
        db.add(item)
        db.flush()
        seen_names[key] = idx
        created.append({"row": idx, "item_code": item.item_code, "item_name": name,
                        "item_type": labels[item_type], "category": category})

    db.commit()
    return {"created": created, "existing": existing, "errors": errors}


@router.get("/export")
async def export_items(
    item_type: str | None = Query(None),
    search: str | None = Query(None),
    category: str | None = Query(None),
    subcategory: str | None = Query(None),
    status: str | None = Query(None),
    db: Session = Depends(get_db),
    _user: User = Depends(require_app_access("store")),
):
    """Excel of the Item Master with the same filters as the list page."""
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill

    query = db.query(StoreItem)
    if item_type:
        query = query.filter(StoreItem.item_type == item_type)
    if category:
        query = query.filter(StoreItem.category == category)
    if subcategory:
        query = query.filter(StoreItem.subcategory == subcategory)
    if status:
        query = query.filter(StoreItem.status == status)
    from app.modules.store.routes.items import apply_item_search, item_search_order
    query = apply_item_search(query, search)
    items = query.order_by(*item_search_order(search)).all()
    labels = {t.value: t.label for t in item_types(db)}

    wb = Workbook()
    ws = wb.active
    ws.title = "Item Master"
    headers = ["Item Code", "Item Type", "Category", "Subcategory", "Item Name", "UOM", "Technical Specification", "Status"]
    ws.append(headers)
    for cell in ws[1]:
        cell.font = Font(bold=True)
        cell.fill = PatternFill("solid", fgColor="FDF1E6")
    for i in items:
        ws.append([i.item_code, labels.get(i.item_type or "", i.item_type or ""), i.category or "", i.subcategory or "",
                   i.item_name, i.uom, i.description or "", (i.status or "").title()])
    for col, width in zip("ABCDEFGH", [16, 18, 24, 20, 34, 8, 36, 12]):
        ws.column_dimensions[col].width = width
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return StreamingResponse(buf, media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                             headers={"Content-Disposition": 'attachment; filename="item_master.xlsx"'})
