-- Tables jo production mein hain par code mein koi model nahi hai
SELECT table_name
  FROM information_schema.tables
 WHERE table_schema = 'public'
   AND table_type   = 'BASE TABLE'
   AND table_name NOT IN ('alembic_version',
       'api_keys',
       'audit_logs',
       'branches',
       'crm_activities',
       'crm_activity_attachments',
       'crm_documents',
       'crm_inquiries',
       'crm_inquiry_approvals',
       'crm_inquiry_line_items',
       'crm_inquiry_tasks',
       'crm_org_contacts',
       'crm_organizations',
       'crm_payment_terms',
       'crm_product_categories',
       'crm_products',
       'crm_purchase_orders',
       'crm_quotation_line_items',
       'crm_quotations',
       'crm_stage_logs',
       'crm_tender_competitors',
       'crm_tender_tasks',
       'crm_tenders',
       'departments',
       'erp_project_attachment_shares',
       'erp_project_attachments',
       'erp_projects',
       'erp_service_material_attachments',
       'erp_service_materials',
       'erp_service_request_attachments',
       'erp_service_requests',
       'feedback',
       'modules',
       'notifications',
       'p2p_goods_receipt_items',
       'p2p_goods_receipts',
       'p2p_purchase_order_items',
       'p2p_purchase_orders',
       'p2p_request_attachments',
       'p2p_request_items',
       'p2p_requests',
       'p2p_vendor_quotations',
       'rfq_attachments',
       'rfqs',
       'rnd_braking_calculations',
       'rnd_calculation_history',
       'rnd_hydraulic_calculations',
       'rnd_load_distribution_calculations',
       'rnd_qmax_calculations',
       'rnd_spline_calculations',
       'rnd_tractive_effort_calculations',
       'rnd_vehicle_performance_calculations',
       'store_locations',
       'user_sessions',
       'users')
 ORDER BY table_name;
