"""extend user model with remote-parity columns

Revision ID: 6f8a8c6a60c7
Revises: ea1db0867f03
Create Date: 2026-07-29 14:01:42.183747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f8a8c6a60c7'
down_revision: Union[str, Sequence[str], None] = 'ea1db0867f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The prior baseline migration now runs Base.metadata.create_all(), which
    # (on a fresh database) already creates `users` with every column the
    # current model defines — including these. Guard each add_column so this
    # migration stays a no-op there, while still adding whatever's actually
    # missing on a database that was provisioned before these columns
    # existed on the model.
    inspector = sa.inspect(op.get_bind())
    existing_columns = {c["name"] for c in inspector.get_columns("users")}

    def add_column_if_missing(column: sa.Column) -> None:
        if column.name not in existing_columns:
            op.add_column("users", column)

    # ### commands auto generated by Alembic - please adjust! ###
    add_column_if_missing(sa.Column('hashed_password', sa.String(), nullable=True))
    add_column_if_missing(sa.Column('azure_display_name', sa.String(), nullable=True))
    add_column_if_missing(sa.Column('profile_photo_url', sa.String(), nullable=True))
    add_column_if_missing(sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    add_column_if_missing(sa.Column('dismissed_announcements', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False))
    add_column_if_missing(sa.Column('encrypted_graph_refresh_token', sa.String(), nullable=True))
    add_column_if_missing(sa.Column('service_permissions', sa.JSON(), nullable=True))
    add_column_if_missing(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    add_column_if_missing(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'service_permissions')
    op.drop_column('users', 'encrypted_graph_refresh_token')
    op.drop_column('users', 'dismissed_announcements')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'profile_photo_url')
    op.drop_column('users', 'azure_display_name')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
