"""baseline

Revision ID: ea1db0867f03
Revises: 
Create Date: 2026-07-29 13:41:24.585775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.base import Base

# revision identifiers, used by Alembic.
revision: str = 'ea1db0867f03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # This migration was originally autogenerated against a dev DB that
    # already had every table (from the pre-Alembic create_all() call), so
    # it only captured a diff (nullable tweaks below) — on a genuinely fresh
    # database it would fail with "relation does not exist". create_all()
    # with checkfirst=True (the default) is idempotent: it creates whatever
    # tables are missing and no-ops on ones that already exist, so this is
    # safe to run against both a brand-new database and an already-migrated
    # one alike. alembic/env.py has already imported every model by the time
    # this runs, so Base.metadata is fully populated here.
    Base.metadata.create_all(bind=op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'assigned_apps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('users', 'erp_permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('users', 'is_azure_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_azure_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'erp_permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('users', 'assigned_apps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    # ### end Alembic commands ###
