'use client'

import UomSelect from '@/components/erp/UomSelect'
import ItemPhoto from '@/components/store/ItemPhoto'
import ItemTypeSelect, { ItemTypeOption } from '@/components/store/ItemTypeSelect'
import CategorySelect from '@/components/store/CategorySelect'
import SubcategorySelect from '@/components/store/SubcategorySelect'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { useRequireApp } from '@/hooks/useAuth'
import { storeApi } from '@/lib/api'
import { StoreItemCategory } from '@/types'
import { TEXT } from '@/lib/theme'
import { Field, Section, Row, inputStyle, primaryBtnStyle, secondaryBtnStyle } from '@/components/shared/ui'
import StoreNav from '@/components/store/StoreNav'
import MessageDialog from '@/components/erp/MessageDialog'
import { extractErrorMessages } from '@/lib/validation'

export default function NewStoreItemPage() {
  const { isAuthorized, isLoading } = useRequireApp('store')
  const router = useRouter()

  const [categories, setCategories] = useState<StoreItemCategory[]>([])
  const [codePreview, setCodePreview] = useState('')
  const [uoms, setUoms] = useState<{ value: string; label: string }[]>([])
  const [itemName, setItemName] = useState('')
  const [itemType, setItemType] = useState('material')
  const [itemTypes, setItemTypes] = useState<ItemTypeOption[]>([])
  const [category, setCategory] = useState('')
  const [subcategory, setSubcategory] = useState('')
  const [description, setDescription] = useState('')
  const [partCode, setPartCode] = useState('')
  const [photo, setPhoto] = useState<File | null>(null)
  const [photoWarning, setPhotoWarning] = useState<{ id: number; message: string } | null>(null)
  const [uom, setUom] = useState('')

  const [busy, setBusy] = useState(false)
  const [errors, setErrors] = useState<string[]>([])

  useEffect(() => {
    if (!isAuthorized) return
    storeApi.listCategories().then(setCategories).catch(() => setCategories([]))
    storeApi.getItemMeta().then((m) => { setUoms(m.uoms); setItemTypes(m.item_types) }).catch(() => setUoms([]))
  }, [isAuthorized])

  // Item code is generated by the server as <TYPE>-<CATEGORY>-<NNNN>; show
  // what it will be for the current type + category (assigned on save).
  useEffect(() => {
    if (!isAuthorized) return
    let cancelled = false
    storeApi.previewItemCode(itemType, category)
      .then((code) => { if (!cancelled) setCodePreview(code) })
      .catch(() => { if (!cancelled) setCodePreview('') })
    return () => { cancelled = true }
  }, [isAuthorized, itemType, category])

  // Only the standard categories for the picked item type.
  const topLevelCategories = categories.filter((c) => !c.parent_id && c.item_type === itemType)
  const selectedCategory = topLevelCategories.find((c) => c.name === category)

  const save = async () => {
    const problems: string[] = []
    if (!itemName.trim()) problems.push('Item Name is required.')
    if (!uom) problems.push('Pick the unit of measure (UOM).')
    if (problems.length) {
      setErrors(problems)
      return
    }
    setBusy(true)
    setErrors([])
    try {
      const item = await storeApi.createItem({
        item_name: itemName.trim(),
        item_type: itemType,
        category: category || undefined,
        subcategory: subcategory || undefined,
        description: description.trim() || undefined,
        part_number: partCode.trim() || undefined,
        uom,
      })
      if (photo) {
        try {
          await storeApi.uploadItemPhoto(item.id, photo)
        } catch (err) {
          // Item is saved; tell the user the photo didn't make it.
          setPhotoWarning({ id: item.id, message: `Item ${item.item_code} was saved, but the photo couldn't be uploaded: ${extractErrorMessages(err, 'upload failed').join(' ')} You can add it from the item page.` })
          return
        }
      }
      router.push(`/dashboard/store/${item.id}`)
    } catch (err) {
      setErrors(extractErrorMessages(err, 'Failed to create item.'))
    } finally {
      setBusy(false)
    }
  }

  if (isLoading || !isAuthorized) return null

  return (
    <div>
      <StoreNav />

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20 }}>
        <div>
          <p style={{ fontSize: 11.5, fontWeight: 600, letterSpacing: '.05em', textTransform: 'uppercase', color: TEXT.muted, margin: '0 0 4px' }}>
            Store &amp; Inventory
          </p>
          <h1 style={{ fontSize: 22, fontWeight: 700, color: TEXT.heading, margin: 0 }}>Add Item</h1>
        </div>
        <button type="button" data-tour="item-back-btn" onClick={() => router.push('/dashboard/store')} style={secondaryBtnStyle}>← Back</button>
      </div>

      <MessageDialog open={errors.length > 0} variant="error" title="Cannot Save Item" message={errors} onClose={() => setErrors([])} />
      <MessageDialog open={!!photoWarning} variant="error" title="Photo Not Uploaded" message={photoWarning?.message || ''}
        onClose={() => photoWarning && router.push(`/dashboard/store/${photoWarning.id}`)} />

      <Section title="Item Details" style={{ marginBottom: 20 }}>
        <Row>
          <Field label="Item Code (auto)">
            <input data-tour="item-code" style={{ ...inputStyle, background: 'rgba(0,0,0,0.04)', color: TEXT.secondary, fontWeight: 600 }} value={codePreview} readOnly
              placeholder="Generated from type + category" title="Assigned automatically when you save: <TYPE>-<CATEGORY>-<NUMBER>" />
          </Field>
          <Field label="Item Type">
            <div data-tour="item-type">
              <ItemTypeSelect value={itemType} onChange={(v) => { if (v !== itemType) { setItemType(v); setCategory(''); setSubcategory('') } }} types={itemTypes} />
            </div>
          </Field>
          <Field label="Category">
            <div data-tour="item-category">
              <CategorySelect itemType={itemType} value={category}
                onChange={(v) => { if (v !== category) { setCategory(v); setSubcategory('') } }} categories={categories} />
            </div>
          </Field>
          <Field label="Subcategory">
            <div data-tour="item-subcategory">
              <SubcategorySelect category={selectedCategory} value={subcategory} onChange={setSubcategory} categories={categories} />
            </div>
          </Field>
        </Row>
        <Row>
          <Field label="Item Name *">
            <input data-tour="item-name" style={inputStyle} value={itemName} onChange={(e) => setItemName(e.target.value)} placeholder="Mild Steel Rod 12mm" />
          </Field>
          <Field label="UOM *">
            <div data-tour="item-uom">
              <UomSelect value={uom} onChange={setUom} options={uoms} onOptionsChange={setUoms} manage={false} />
            </div>
          </Field>
          <Field label="Part Code (optional)">
            <input data-tour="item-part-code" style={inputStyle} value={partCode} onChange={(e) => setPartCode(e.target.value)} placeholder="Part code" />
          </Field>
        </Row>
        <Field label="Technical Specification">
          <textarea data-tour="item-description" style={{ ...inputStyle, minHeight: 70, resize: 'vertical' }} value={description} onChange={(e) => setDescription(e.target.value)} />
        </Field>
      </Section>

      <Section title="Photo" style={{ marginBottom: 20 }}>
        <div data-tour="item-photo">
          <ItemPhoto pending={photo} onPendingChange={setPhoto} />
        </div>
      </Section>

      <div style={{ display: 'flex', gap: 10 }}>
        <button data-tour="item-save-btn" disabled={busy} onClick={save} style={{ ...primaryBtnStyle, opacity: busy ? 0.7 : 1 }}>{busy ? 'Saving…' : 'Save Item'}</button>
        <button data-tour="item-cancel-btn" disabled={busy} onClick={() => router.push('/dashboard/store')} style={{ ...secondaryBtnStyle, opacity: busy ? 0.6 : 1 }}>Cancel</button>
      </div>
    </div>
  )
}
